name: deploy

on:
  push:
    branches: [main]

jobs:
  terraform:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'test')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Apply
        run: make deploy
        env:
          TF_VAR_project_name: ${{ secrets.PROJECT_NAME }}
          TF_VAR_credential_file: ${{ secrets.CREDENTIAL_FILE }}
          TF_VAR_region: ${{ secrets.REGION }}
          TF_VAR_bucket_name: ${{ secrets.BUCKET_NAME }}
